language: node_js  #设置语言

node_js: "lts/*"  #设置相应的版本

install:
- yarn  #安装hexo及插件

before_script:
- cd themes/xiao
- yarn
- cd ../..

script:
- hexo cl  #清除
- hexo g  #生成

after_script:
- cd ./public
- git init
- git config user.name "ghostsf"  #修改name
- git config user.email "ghost_sf@163.com"  #修改email
- git add .
- git commit -m "update"
- git push --force --quiet "https://${github-token}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
  - hexo  #只监测hexo分支，可根据自己情况设置
env:
  global:
  - GH_REF: github.com/ghostsf/ghostsf.com.git  #设置GH_REF

cache:
  yarn: true
  directories:
  - node_modules
